Attribute VB_Name = "JobAdminResource"
' Gobal string ID for RC String Table
' Generated Form:	C:\Projects\LucentTechnologiesSP\JobAdmin\JobAdmin Resource.doc
' Generated On: 	05/06/97 9:17 AM
'//	Form captions
Global Const resFORM_MAIN_CAPTION = 10
Global Const resFORM_ADD_DATA_POINT = 11
Global Const resFORM_OPEN_JOB_FILE = 12
Global Const resLABEL_SPLASH_LOGO = 13
'//	Menu captions
Global Const resMNU_FILE = 300
Global Const resMNU_EXIT = 301
Global Const resMNU_OPEN = 302
Global Const resMNU_HELP = 303
Global Const resMNU_CONTENTS = 304
Global Const resMNU_SEARCH = 305
Global Const resMNU_ABOUT = 306
Global Const resMNU_VIEW = 307
Global Const resMNU_JOBS = 308
Global Const resMNU_GLOBAL = 309
'//	Tab control labels
Global Const resTAB_JOBS = 400
Global Const resTAB_GLOBAL = 401
'//	Form labels
Global Const resLABEL_JOB_NAME = 500
Global Const resLABEL_COMCODE = 501
Global Const resLABEL_STARTING_SN = 502
Global Const resLABEL_PLANT_CODE = 503
Global Const resLABEL_COMCODE_DB_PATH = 504
Global Const resLABEL_COMCODE_TABEL = 505
Global Const resLABEL_TEMPLATE_NAME = 506
Global Const resLABEL_TEMPLATE_PATH = 507
Global Const resLABEL_TEMPLATE = 508
Global Const resLABEL_LOCATIONS = 509
Global Const resLABEL_X_AXIS = 510
Global Const resLABEL_Y_AXIS = 511
Global Const resLABEL_THATA = 512
Global Const resLABEL_DATA_CONTROL = 513
Global Const resLABEL_USE_GLOBAL_SN = 514
Global Const resLABEL_GLOBAL_SN = 515
Global Const resLABEL_DEFLAT_PLANT_CODE = 516
Global Const resLABEL_LUCENT_YEAR = 517
Global Const resLABEL_LUCENT_WEEK = 518
Global Const resLABEL_FIRST_WEEK = 519
'//	Command buttons captions
Global Const resCMD_SAVE = 600
Global Const resCMD_DELETE = 601
Global Const resCMD_NEW = 602
Global Const resCMD_OK = 603
Global Const resCMD_CANCEL = 604
'//	Information messages
Global Const resMSG_TITEL = 700
Global Const resMSG_GLOBAL_SAVE = 701
Global Const resMSG_JOB_SAVE = 702
Global Const resMSG_THATA_BAD = 703
Global Const resTITLE_BAD_ENTRY = 704
'//	Misalliances messages 
Global Const resJOB_FILE_FILTER = 3000
'//	Status help messages 
Global Const resSTMSG_JOB_FILE = 5000
Global Const resSTMSG_JOB_NAME = 5001
Global Const resSTMSG_COMCODE = 5002
Global Const resSTMSG_SERIAL = 5003
Global Const resSTMSG_PLANT_CODE = 5004
Global Const resSTMSG_DB_PATH = 5005
Global Const resSTMSG_TABLE_NAME = 5006
Global Const resSTMSG_LABEL_NAME = 5007
Global Const resSTMSG_LABEL_PATH = 5008
Global Const resSTMSG_LABEL_TEMPLATE = 5009
Global Const resSTMSG_LABEL_DATA = 5010
Global Const resSTMSG_NEW_DP = 5011
Global Const resSTMSG_SAVE_JOB = 5012
Global Const resSTMSG_NEW_JOB = 5013
Global Const resSTMSG_DELETE = 5014
Global Const resSTMSG_DB_CONTROL = 5015
Global Const resSTMSG_GLOBAL = 5016
Global Const resSTMSG_USE_GLOBAL = 5017
Global Const resSTMSG_INIT_SN = 5018
Global Const resSTMSG_PLANT_DEFALT = 5019
Global Const resSTMSG_YEAR_CODE = 5020
Global Const resSTMSG_CURRENT_WEEK = 5021
Global Const resSTMSG_WEEK_CODE = 5022
Global Const resSTMSG_SAVE_GLOBAL = 5023
Global Const resSTMSG_ADD_DP = 5024
Global Const resSTMSG_LABEL_X_AXIS = 5025
Global Const resSTMSG_LABEL_Y_AXIS = 5026
Global Const resSTMSG_LABEL_THETA = 5027
Global Const resSTMSG_DP_OK = 5028
Global Const resSTMSG_DP_CANCEL = 5029
' End of String Resources
