//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by PACS.rc
//
#define ID_UPDATE                       3
#define IDHOME                          3
#define IDP_OLE_INIT_FAILED             100
#define IDS_ABOUTBOX                    101
#define IDP_SOCKETS_INIT_FAILED         103
#define IDS_APP_DOORS                   106
#define IDS_ERR_EE_RETRACT              107
#define IDS_ERR_MOVE_PLACE              108
#define IDS_ERR_CONVEYOR                109
#define IDS_ERR_STILL_CONVEYOR          110
#define IDS_ERR_EE_EXTEND               111
#define IDS_ERR_MOVE_SCAN               112
#define IDS_REMOVE_BOARDS               113
#define IDS_INVALID_LENGTH              114
#define IDS_INVALID_NUMERIC             115
#define IDS_INVALID_ROTATION            116
#define IDS_INVALID_JOBTEXT_LENGTH      117
#define IDS_SN_INTERFACE_ERROR          118
#define IDS_INVALID_DATA_CONSTRAINT     119
#define IDS_INVALID_INTERVAL            120
#define IDS_INIT_DATABASE_ERR           121
#define IDS_INVALID_PRINTER_DATABASE    122
#define IDS_NO_STATA_DATA               123
#define IDS_NO_POINT_DATA               124
#define IDS_INVALID_POSITION            125
#define IDS_NO_POINT_TABLE              126
#define IDS_NO_SCANNING_RECORDS         127
#define IDR_MAINFRAME                   128
#define IDS_UNSUPPORTED_SCANNER         128
#define IDS_NO_DATABASE                 129
#define IDS_INVALID_COMPORT_DATABASE    130
#define IDB_HELP                        131
#define IDS_ERR_OPEN_COMPORT            131
#define IDD_BYPASS_DIALOG               131
#define IDD_SETUP_DLG                   132
#define IDS_ERR_PRINTER_INIT            132
#define IDS_ERR_PRINTER_RESP            133
#define IDD_SYSTEM_SETUP_DLG            134
#define IDS_PRINTER_OUTOFPAPER          134
#define IDS_PRINTER_INPAUSE             135
#define IDD_SETUP_SCANNER_DLG           136
#define IDS_PRINTER_BUFFERFULL          136
#define IDS_PRINTER_BADRAM              137
#define IDD_CHANGE_PASSWORD_DLG         138
#define IDS_PRINTER_HEADUP              138
#define IDS_PRINTER_RIBBONOUT           139
#define IDD_EDIT_JOB_DLG                140
#define IDS_PRINTER_STRIPPIN            140
#define IDS_ERR_SCANNER_RESET_STRING    141
#define IDD_POINT_DLG                   142
#define IDS_SCANNER_RESET_ERR           142
#define IDS_ERR_CONVEYOR_INIT           143
#define IDD_UPDATE_INTERVAL_DLG         144
#define IDS_INVALID_CONVEYORIO_DATABASE 144
#define IDS_ERR_INIT_DIO                145
#define IDD_INIT_DLG_MESSAGE            146
#define IDS_INVALID_SYSTEMIO_DATABASE   146
#define IDS_INVALID_MC                  147
#define IDI_COMPUTYPE                   148
#define IDS_ERR_CONTROLLER_COM          148
#define IDD_DIALOG1                     149
#define IDS_ERR_CONTROLLER_RESPOND      149
#define IDS_ERR_SERVO_ON                150
#define IDD_PASSWORD_DLG                150
#define IDS_ERR_SERVO_OFF               151
#define IDS_ERR_SERVO_HOME              152
#define IDD_SETUP_PRINTER_DLG           152
#define IDS_ERR_SERVO_MOTION            153
#define IDS_ERR_SERVO_ACCEL             154
#define IDD_DATABASE_PANEL_LABEL_SETUP_DLG 154
#define IDS_CONVEYOR_ERR                155
#define IDS_ERR_POWER_OFF               156
#define IDD_TEMPLATE_EDIT_DLG           156
#define IDS_ERR_DOOR_OPEN               157
#define IDS_ERR_NO_AIR                  158
#define IDD_TEMPLATENAME_DLG            158
#define IDS_BYPASS_ON                   159
#define IDS_NO_PASSWORD_DATA            160
#define IDD_DELETE_JOB_DLG              160
#define IDS_ORIGIN_ERR_TYPE             161
#define IDS_PARK_ERR_TYPE               162
#define IDD_PRINTER_SELECT              162
#define IDD_SELECT_PRINTER_DLG          162
#define IDS_NP1_OFFSET0_ERR_TYPE        163
#define IDS_NP1_OFFSET90_ERR_TYPE       164
#define IDD_HOLD_DLG                    164
#define IDS_NP2_OFFSET0_ERR_TYPE        165
#define IDD_RUN_DIALOG                  165
#define IDS_NP2_OFFSET90_ERR_TYPE       166
#define IDS_SCANNERNP1_OFFSET0_ERR_TYPE 167
#define IDS_SCANNERNP1_OFFSET90_ERR_TYPE 168
#define IDD_ADD_EDIT_JOB_DLG            168
#define IDS_SCANNERNP2_OFFSET0_ERR_TYPE 169
#define IDS_SCANNERNP2_OFFSET90_ERR_TYPE 170
#define IDD_DB_PANEL_LABEL_DLG          170
#define IDS_NO_STATISTICS_DATA          171
#define IDS_INVALID_PREPICKPOS          172
#define IDD_SETUP_FEEDER_DLG            172
#define IDS_INVALID_PICKPOS             173
#define IDS_INVALID_PORTID              174
#define IDD_RESCAN_DLG                  174
#define IDS_ERR_SCANNER_INIT            175
#define IDS_CONVEYOR_ERROR              176
#define IDD_MC_DIAGNOSTICS              176
#define IDS_INVALID_CONVEYORINFO_DATABASE 177
#define IDS_INVALID_MOTION_DATABASE     178
#define IDD_DIAG_MSG_DLG                178
#define IDS_INVALID_SN                  179
#define IDS_INVALID_PRINTER_TYPE        180
#define IDD_JOB_NAME_DLG                180
#define IDS_NO_SN_DATABASE              181
#define IDD_PRINTER_DIAGNOSTICS         181
#define IDS_NO_RETRY_DATA               182
#define IDD_INTERNAL_SETUP_DLG          182
#define IDS_SCANNER_UPDATE_ERR          183
#define IDD_DIO_DIAGNOSTICS             183
#define IDS_ERR_SCANNER_RESPONSE        184
#define IDD_LABEL_SELECT_DLG            184
#define IDS_SCANNER_NOREAD              185
#define IDD_DIAGNOSTICS                 185
#define IDS_ERR_PRINTER_REFRESH         186
#define IDD_SCANNER_DIAGNOSTICS         186
#define IDS_CONVEYOR_CONTROL_CHANGE     187
#define IDD_WYSIWYG_PANEL_LABEL_DLG     187
#define IDS_NO_MATCHING_DATABASE_TEMP   188
#define IDS_ERR_JOB_DELETE              189
#define IDD_LABELS_PER_CYCLE            189
#define IDS_TEMPLATE_CHANGED            190
#define IDS_ERR_SET_JOB                 191
#define IDD_SETUP_SERIALIZATION_DLG     191
#define IDS_NO_WYSIWYG_DATA             192
#define IDS_PRINTER_TYPE_ERR            193
#define IDD_INTERNAL_SETUP_DL           193
#define IDS_ERR_MOVE_TO_PARK            194
#define IDS_ERR_RETRACT                 195
#define IDD_TEMPLATE_SETUP              195
#define IDS_CLOSE_DOORS                 196
#define IDS_CREATE_RUN_ERR              197
#define IDD_STARTUP_ERRORS              197
#define IDS_ERR_EE_NOT_EXTEND           198
#define IDS_ERR_ROTATION                199
#define IDD_PRINTER_TYPE_DLG            199
#define IDS_HOME_ERR                    200
#define IDS_ERR_FEEDER1_INIT            201
#define IDS_ERR_FEEDER2_INIT            202
#define IDD_DIALOG2                     202
#define IDS_INVALID_FEEDER_DATABASE     203
#define IDD_TEACH                       203
#define IDS_NO_TEMPLATES                204
#define IDS_ERR_ENABLE_FEEDER           205
#define IDS_ERR_FEEDER_MOTOR            206
#define IDB_TEACH_UPARROW               206
#define IDS_ERR_FEEDER_ADVANCE          207
#define IDB_TEACH_DOWNARROW             207
#define IDS_ERR_FEEDER_REFRESH          208
#define IDB_TEACH_LEFTARROW             208
#define IDS_ERR_LABEL_COUNT             209
#define IDB_TEACH_RIGHTARROW            209
#define IDS_INVALID_LABEL_ATT           210
#define IDS_NO_GENERAL_RECORDS          211
#define IDS_ERR_PANEL_DIM               212
#define IDS_EMPTY_LABEL_LIST            213
#define IDS_ERR_LABEL_LIST              214
#define IDS_INVALID_JOBNAME             215
#define IDS_INVALID_DEVICE              216
#define IDS_INVALID_DIO_ADDRESS         217
#define IDS_INVALID_MULTISEL_SPEED      218
#define IDS_INVALID_SUPERSEL_SPEED      219
#define IDS_INVALID_ACCEL               220
#define IDS_RESTART_WARNING             221
#define IDS_INVALID_PANEL               222
#define IDS_ERR_PRINTER_CREATION        223
#define IDS_SELECT_LABEL                224
#define IDS_ERR_GET_SN                  225
#define IDS_ERR_SET_SN                  226
#define IDS_ERR_INIT_SN                 227
#define IDS_PRINTER_DISABLED            228
#define IDS_USE_DISABLED_PRINTER        229
#define IDS_ERR_FRONT_DOWNSTREAM_PRINTER_INIT 230
#define IDS_ERR_BACK_UPSTREAM_PRINTER_INIT 231
#define IDS_ERR_BACK_DOWNSTREAM_PRINTER_INIT 232
#define IDS_ERR_OFFLINE_PRINTER1_INIT   233
#define IDS_ERR_OFFLINE_PRINTER2_INIT   234
#define IDS_ERR_SUPERSEL_INIT           235
#define IDS_ERR_MULTISEL_INIT           236
#define IDS_ERR_PLACEMENT_SCANNER_INIT  237
#define IDS_ERR_SYSTEM_SCANNER_INIT     238
#define IDS_ERR_UNRECOGNIZED_FORMAT_STRING 239
#define IDS_INVALID_RESERVED_WORD_VALUE 240
#define IDS_DATABASE_INIT_ERROR         241
#define IDS_ERROR_INPUT_BITS_DESC       242
#define IDS_DUPLICATE_JOB_EXIST         243
#define IDS_INVALID_PW                  244
#define IDS_INVALID_SYSPW               245
#define IDS_NO_STATISTICAL_DATABASE     246
#define IDS_WARNING_WYSIWYG             247
#define IDS_ERR_SERIALNUMBER_LENGTH     248
#define IDS_WARNING_TEMPLATE_ACTIVE     249
#define IDC_JOB_DATA_LIST               1001
#define IDC_DATETIME_LABEL              1002
#define IDC_CMD_ADDJOB                  1003
#define IDC_CMD_EDITJOB                 1004
#define IDC_CMD_SYSTEMSETUP             1005
#define IDC_SCANNERTYPE                 1005
#define IDC_PLACEMENT_SCANNERTYPE       1005
#define IDC_CMD_RUN                     1006
#define IDC_CMD_PRINTERSETUP            1006
#define IDC_SYSTEM_SCANNERTYPE          1006
#define IDC_CMD_FEED                    1007
#define IDC_CMD_CHANGEPW                1007
#define IDC_INITIALIZATION_STRING       1007
#define IDC_LABEL33                     1007
#define IDC_PLACEMENT_INITIALIZATION_STRING 1007
#define IDC_CMD_PRINT                   1008
#define IDC_USEPC                       1008
#define IDC_SYSTEM_INITIALIZATION_STRING 1008
#define IDC_CMD_FEEDERSETUP             1008
#define IDC_CMD_BYPASS                  1009
#define IDC_CMD_SCANNERSETUP            1009
#define IDC_USEPLC                      1009
#define IDC_CMD_PARK                    1010
#define IDC_RIGHTTOLEFT                 1010
#define IDC_CMD_DELETEJOB               1010
#define IDC_CMD_DIAGNOSTICS             1011
#define IDC_LEFTTORIGHT                 1011
#define IDC_JOB_NAME                    1014
#define IDC_EDITLABEL                   1015
#define IDC_PRINTER_TYPE                1017
#define IDC_LABEL42                     1017
#define IDC_ENABLE                      1018
#define IDC_LABEL43                     1018
#define IDC_JOBLBL                      1019
#define IDC_X_PREPICK                   1019
#define IDC_LABEL44                     1019
#define IDC_Y_PREPICK                   1020
#define IDC_LABEL45                     1020
#define IDC_X_PICK                      1021
#define IDC_LABEL46                     1021
#define IDC_Y_PICK                      1022
#define IDC_LABEL47                     1022
#define IDC_JOB_LIST                    1023
#define IDC_LABEL48                     1023
#define IDC_OPT_FRONT_DOWNSTREAM        1025
#define IDC_OPT_BACK_DOWNSTREAM         1026
#define IDC_OPT_UPSTREAM_FEEDER         1027
#define IDC_PRINTER_TYPES               1027
#define IDC_LIST_JOBS                   1028
#define IDC_POINT_EDIT                  1028
#define IDC_LIST_JOB                    1028
#define IDC_TEMPLATE_EDIT               1029
#define IDC_TEMPLATE_TEST               1030
#define IDC_POINT_ADD                   1034
#define IDC_POINT_DELETE                1035
#define IDC_LABEL11                     1037
#define IDC_LABEL12                     1040
#define IDC_LABEL13                     1041
#define IDC_LABEL17                     1042
#define IDC_USE_DESIGNER                1042
#define IDC_LABEL29                     1043
#define IDC_ENABLE_FEEDER               1043
#define IDC_LABEL16                     1044
#define IDC_FEEDER_SELECTION            1044
#define IDC_ADVANCE_DELAY               1045
#define IDC_ENABLE_SCAN                 1047
#define IDC_JOBNAME                     1048
#define IDC_PANEL_PROGRESS              1049
#define IDC_PRINTER_SELECTED            1052
#define IDC_CMD_BYPASS_EXIT             1052
#define IDC_LIST_LOCATION               1053
#define IDC_SELECTED_SCANNER            1053
#define IDC_DATA1                       1055
#define IDC_DATA2                       1056
#define IDC_EDIT_X                      1057
#define IDC_USE_WYSIWYG                 1057
#define IDC_COUNTRY_CODE                1057
#define IDC_EDIT_Y                      1058
#define IDC_PANEL_SELECTION             1058
#define IDC_LABELS_PER_CYCLE            1058
#define IDC_RELEASE                     1058
#define IDC_BROWSE                      1059
#define IDC_OPTION_0                    1061
#define IDC_YOFFSET2                    1061
#define IDC_OPTION_90                   1062
#define IDC_XOFFSET                     1062
#define IDC_YOFFSET                     1063
#define IDC_EDIT1                       1063
#define IDC_EDIT2                       1064
#define IDC_USE_SERIALIZATION           1064
#define IDC_SETUP_SERIALIZATION         1065
#define IDC_EDIT3                       1065
#define IDC_LABEL2                      1066
#define IDC_LABEL3                      1067
#define IDC_EDIT4                       1067
#define IDC_LABEL18                     1068
#define IDC_SN_TYPE                     1068
#define IDC_LABEL5                      1069
#define IDC_SN_LENGTH                   1069
#define IDC_LABEL51                     1069
#define IDC_LABEL21                     1070
#define IDC_ONE_UP                      1070
#define IDC_LABEL54                     1070
#define IDC_LABEL31                     1071
#define IDC_TWO_UP                      1071
#define IDC_LABEL55                     1071
#define IDC_LABEL32                     1072
#define IDC_LABEL52                     1072
#define IDC_LABEL56                     1072
#define IDC_LABEL37                     1073
#define IDC_ONE_NOSEPIECE               1073
#define IDC_PANEL_COUNT                 1074
#define IDC_LABEL38                     1074
#define IDC_TWO_NOSEPIECES              1074
#define IDC_LABEL_COUNT                 1075
#define IDC_DELETE                      1075
#define IDC_LABEL34                     1076
#define IDC_CURRENT_SN                  1076
#define IDC_EDIT                        1076
#define IDC_LABEL_RUN_SERIAL            1079
#define IDC_2UP_JOB                     1079
#define IDC_MANUFACTURING_SITE          1080
#define IDC_COUNTRY                     1081
#define IDC_REST_POSITIONX              1082
#define IDC_REST_POSITIONY              1083
#define IDC_USESTATICDATECODE           1084
#define IDC_STATICDATECODE              1085
#define IDC_LABEL_MATCH                 1086
#define IDC_TEXTBOX1                    1090
#define IDC_DATABASE_LABEL              1091
#define IDC_CONVEYOR_LABEL              1092
#define IDC_DIO_LABEL                   1093
#define IDC_FEEDER_LABEL                1094
#define IDC_MOTION_LABEL                1095
#define IDC_PRINTER_LABEL               1096
#define IDC_JOB_INFO                    1096
#define IDC_SCANNER_LABEL               1097
#define IDC_JOB_NAMES                   1097
#define IDC_JOB_INFO_FG                 1098
#define IDC_CUSTOMER_LABEL              1098
#define IDC_CMD_SETUPJOB                1099
#define IDC_OK                          1099
#define IDC_SAVEASNEW                   1099
#define IDC_CMD_HOLD                    1099
#define IDC_RELABELBUTTON               1099
#define IDC_SCANNER_DIAGNOSTICS         1099
#define IDC_SET_OUTPUT_ADDRESS          1099
#define IDC_SERVO_TOGGLE                1099
#define IDC_SET_RESET_STRING            1099
#define IDC_LABEL_POINTS_FG             1099
#define IDC_EDT_CUSTOMER                1099
#define IDC_DIO_DIAGNOSTICS             1100
#define IDC_HOME                        1100
#define IDC_SERIAL_FRAME                1100
#define IDC_LABEL4                      1101
#define IDC_PRINTER_DIAGNOSTICS         1101
#define IDC_SET_INPUT_ADDRESS           1101
#define IDC_LABEL30                     1102
#define IDC_LABEL_PRINTER1_STATUS       1102
#define IDC_MC_DIAGNOSTICS              1102
#define IDC_FG_JOB_STATUS               1102
#define IDC_LABEL8                      1103
#define IDC_CANCEL                      1174
#define IDC_NEW_YPOS                    1174
#define IDC_UPDATE_JOB                  1175
#define IDC_TEMPLATE_NAME               1175
#define IDC_DELETEJOB                   1175
#define IDC_LEFT_BUTTON                 1175
#define IDC_EDIT_PANEL_LABEL            1176
#define IDC_RIGHT_BUTTON                1176
#define IDC_TEACH_PPICK                 1176
#define IDC_STEP_SIZE                   1177
#define IDC_TEACH_PICK                  1177
#define IDC_ABOUTBUTTON                 1178
#define IDC_SINGLE_TRIGGER              1178
#define IDC_TOP_BUTTON                  1178
#define IDC_STATISTICS_FILE             1179
#define IDC_CONTINUOUS_TRIGGER          1179
#define IDC_BOTTOM_BUTTON               1179
#define IDC_EDT_JOG_SPEED               1180
#define IDC_MANUAL_FEED                 1181
#define IDC_LBLMETRICS                  1182
#define IDC_LBLJOBDETAILS               1183
#define IDC_RESET_JULIAN                1183
#define IDC_AUTO_REPICKS                1185
#define IDC_AUTO_RESCANS                1186
#define IDC_LABEL24                     1187
#define IDC_REFRESH_LIST                1188
#define IDC_PANEL_QUANTITY              1189
#define IDC_LABEL25                     1189
#define IDC_CUSTOMER                    1190
#define IDC_LABEL36                     1190
#define IDC_PRODUCT_CODE                1190
#define IDC_CLOSE_MC_DIAGNOSTICS        1192
#define IDC_CLOSE_SCANNER_DIAGNOSTICS   1193
#define IDC_CLOSE_PRINTER_DIAGNOSTICS   1194
#define IDC_FORM_FEED                   1297
#define IDC_SET_DEFAULTS                1299
#define IDC_PRINTER_STATUS              1300
#define IDC_VERSION_STRING              1301
#define IDC_ACTUATOR_POSITION           1302
#define IDC_RESET_STRING                1303
#define IDC_SCAN_RESULTS                1306

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        210
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1184
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
