Attribute VB_Name = "JobAdminResource"
' Gobal string ID for RC String Table
' Generated Form:           \\NEXSTEP1\NEXSTEP\SoftwareDevelopment\Projects\Motorola_FL\JobAdmin\JobAdmin Resource.doc
' Generated On:             09/05/97 5:32 PM
'//           Form captions
Global Const resFORM_MAIN_CAPTION = 10 
Global Const resFORM_ADD_DATA_POINT = 11 
Global Const resFORM_OPEN_JOB_FILE = 12 
Global Const resLABEL_SPLASH_LOGO = 13 
'//           Menu captions
Global Const resMNU_FILE = 300 
Global Const resMNU_EXIT = 301 
Global Const resMNU_OPEN = 302 
Global Const resMNU_HELP = 303 
Global Const resMNU_CONTENTS = 304 
Global Const resMNU_ABOUT = 305 
'//           Tab control labels
Global Const resTAB_JOBS = 400 
Global Const resTAB_COMMON = 401 
'//           Form labels
Global Const resLABEL_JOB_NAME = 500 
Global Const resLABEL_PART_NUMBER = 501 
Global Const resLABEL_LOCATION_CODE = 502 
Global Const resLABEL_TEMPLATE_NAME = 503 
Global Const resLABEL_TEMPLATE_PATH = 504 
Global Const resLABEL_LABEL_LOCATION = 505 
Global Const resLABEL_LAST_SEQ_NUMBER = 506 
Global Const resLABEL_LINE_CODE = 507 
Global Const resLABEL_SCAN_TRIES = 508 
Global Const resLABEL_KIT_FILE_NAME = 509 
Global Const resLABEL_KIT_FILE_PATH = 510 
Global Const resLABEL_LOG_FILE_NAME = 511 
Global Const resLABEL_LOG_FILE_PATH = 512 
'//           Command buttons captions
Global Const resCMD_SAVE = 600 
Global Const resCMD_DELETE = 601 
Global Const resCMD_NEW = 602 
Global Const resCMD_OK = 603 
Global Const resCMD_CANCEL = 604 
'//           Information messages
Global Const resMSG_TITEL = 700 
Global Const resMSG_JOB_SAVE = 701 
Global Const resMSG_THATA_BAD = 702 
Global Const resTITLE_BAD_ENTRY = 703 
Global Const resLABEL_DATA_CONTROL = 704 
'//           Misalliances messages 
Global Const resJOB_FILE_FILTER = 3000 
'//           Status help messages 
Global Const resSTMSG_JOB_FILE = 5000 
Global Const resSTMSG_JOB_NAME = 5001 
Global Const resSTMSG_PART_NUMBER = 5002 
Global Const resSTMSG_LOCATION_CODE = 5003 
Global Const resSTMSG_TEMPLATE_NAME = 5004 
Global Const resSTMSG_TEMPLATE_PATH = 5005 
Global Const resSTMSG_SAVE_JOB = 5006 
Global Const resSTMSG_NEW_JOB = 5007 
Global Const resSTMSG_DELETE = 5008 
Global Const resSTMSG_LAST_SEQ_NUMBER = 5009 
Global Const resSTMSG_DB_CONTROL = 5010 
Global Const resSTMSG_LINE_CODE = 5011 
Global Const resSTMSG_KIT_FILE_NAME = 5012 
Global Const resSTMSG_KIT_FILE_PATH = 5013 
Global Const resSTMSG_LOG_FILE_NAME = 5014 
Global Const resSTMSG_LOG_FILE_PATH = 5015 
Global Const resSTMSG_SCAN_TRIES = 5016 
' End of String Resources
