copy InternalSetupDLL\nsinternalsetup\debug\*.lib c:\NSLibs\*.*

copy NSAddEditJobDlg\debug\*.lib c:\NSLibs\*.*
copy NSChangePasswordDlg\debug\*.lib c:\NSLibs\*.*
copy NSDatabase\debug\*.lib c:\NSLibs\*.*
copy NSDeleteJobDlg\debug\*.lib c:\NSLibs\*.*
copy NSDIO\debug\*.lib c:\NSLibs\*.*
copy NSDIODiagnostic\debug\*.lib c:\NSLibs\*.*
copy NSEnTerJobNameDlg\debug\*.lib c:\NSLibs\*.*
copy NSHoldDlg\debug\*.lib c:\NSLibs\*.*
copy NSJobs\debug\*.lib c:\NSLibs\*.*
copy NSLabelSelectDlg\debug\*.lib c:\NSLibs\*.*
copy NSLibrary\debug\*.lib c:\NSLibs\*.*
copy NSMSFlexGrid\debug\*.lib c:\NSLibs\*.*
copy NSPanelLabelDlg\debug\*.lib c:\NSLibs\*.*
copy NSPasswordDlg\debug\*.lib c:\NSLibs\*.*
copy NSPointDlg\debug\*.lib c:\NSLibs\*.*
copy NSPrinterSelectDlg\debug\*.lib c:\NSLibs\*.*
copy NSSerializationDlg\debug\*.lib c:\NSLibs\*.*
copy NSSetupScannerDlg\debug\*.lib c:\NSLibs\*.*
copy NSStatisticsDB\debug\*.lib c:\NSLibs\*.*
copy NSSystemDB\debug\*.lib c:\NSLibs\*.*
copy NSTEmplateEditDlg\debug\*.lib c:\NSLibs\*.*
copy NSTemplateSetupDlg\debug\*.lib c:\NSLibs\*.*
copy NSTemplateNameDlg\debug\*.lib c:\NSLibs\*.*
copy NSUpdateIntervalDlg\debug\*.lib c:\NSLibs\*.*
copy NSUtility\debug\*.lib c:\NSLibs\*.*
