//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by NSInternalSetup.rc
//
#define ID_UPDATE                       3
#define IDCAPTURE                       5
#define IDS_ABOUTBOX                    101
#define IDC_LABEL19						106
#define IDC_LABEL35						107
#define IDS_INVALID_LENGTH              114
#define IDS_INVALID_NUMERIC             115
#define IDS_INVALID_ROTATION            116
#define IDS_INVALID_JOBTEXT_LENGTH      117
#define IDS_INIT_DATABASE_ERR			121
#define IDS_NO_DATABASE                 129
#define IDS_INVALID_COMPORT_DATABASE    130
#define IDS_ERR_OPEN_COMPORT            131
#define IDD_BYPASS_DIALOG               131
#define IDD_SYSTEM_SETUP_DLG            134
#define IDD_INIT_DLG_MESSAGE            146
#define IDS_INVALID_SYSTEMIO_DATABASE   146
#define IDS_INVALID_PORTID              174
#define IDS_INVALID_SN                  179
#define IDS_INVALID_PRINTER_TYPE        180
#define IDD_INTERNAL_SETUP_DLG          182
#define IDD_DIO_DIAGNOSTICS             183
#define IDS_ERR_SCANNER_RESPONSE        184
#define IDD_LABEL_SELECT_DLG            184
#define IDS_SCANNER_NOREAD              185
#define IDD_DIAGNOSTICS                 185
#define IDS_ERR_PRINTER_REFRESH         186
#define IDD_INTERNAL_SETUP_DL           193
#define IDS_NO_GENERAL_RECORDS          211
#define IDS_ERR_PANEL_DIM               212
#define IDS_EMPTY_LABEL_LIST            213
#define IDS_ERR_LABEL_LIST              214
#define IDS_INVALID_JOBNAME             215
#define IDS_INVALID_DEVICE              216
#define IDS_INVALID_DIO_ADDRESS         217
#define IDS_INVALID_PANEL               222
#define IDS_ERR_PRINTER_CREATION        223
#define IDS_SELECT_LABEL                224
#define IDS_DATABASE_INIT_ERROR         241
#define IDS_ERROR_INPUT_BITS_DESC       242
#define IDS_DUPLICATE_JOB_EXIST         243
#define IDS_INVALID_PW                  244
#define IDS_INVALID_SYSPW               245
#define IDS_NO_STATISTICAL_DATABASE     246
#define IDS_WARNING_WYSIWYG             247
#define IDS_ERR_SERIALNUMBER_LENGTH     248
#define IDS_WARNING_TEMPLATE_ACTIVE     249
#define IDC_JOB_DATA_LIST               1001
#define IDC_LABEL7                      1002
#define IDC_SCANNERTYPE                 1005
#define IDC_PLACEMENT_SCANNERTYPE       1005
#define IDC_CMD_RUN                     1006
#define IDC_CMD_PRINTERSETUP            1006
#define IDC_SYSTEM_SCANNERTYPE          1006
#define IDC_CMD_FEED                    1007
#define IDC_CMD_CHANGEPW                1007
#define IDC_INITIALIZATION_STRING       1007
#define IDC_LABEL33                     1007
#define IDC_PLACEMENT_INITIALIZATION_STRING 1007

#define IDC_CMD_PRINT                   1008
#define IDC_USEPC                       1008
#define IDC_SYSTEM_INITIALIZATION_STRING 1008
#define IDC_CMD_FEEDERSETUP             1008
#define IDC_CMD_BYPASS                  1009
#define IDC_CMD_SCANNERSETUP            1009
#define IDC_LEFTTORIGHT                 1011
#define IDC_LABEL1                      1012
#define IDC_LABEL9                      1013
#define IDC_JOB_NAME                    1014
#define IDC_LABEL39                     1014
#define IDC_EDITLABEL                   1015
#define IDC_UPDATE                      1015
#define IDC_LABEL43                     1018
#define IDC_JOBLBL                      1019
#define IDC_LABEL11                     1037
#define IDC_LABEL12                     1040
#define IDC_LABEL13                     1041
#define IDC_LABEL17                     1042
#define IDC_USE_DESIGNER                1042
#define IDC_LABEL29                     1043
#define IDC_ENABLE_FEEDER               1043
#define IDC_LABEL16                     1044
#define IDC_FEEDER_SELECTION            1044
#define IDC_ADVANCE_DELAY               1045
#define IDC_ENABLE_SCAN                 1047
#define IDC_JOBNAME                     1048
#define IDC_PANEL_PROGRESS              1049
#define IDC_PRINTER_SELECTED            1052
#define IDC_CMD_BYPASS_EXIT             1052
#define IDC_LIST_LOCATION               1053
#define IDC_SELECTED_SCANNER            1053
#define IDC_LABEL2                      1066
#define IDC_LABEL3                      1067
#define IDC_EDIT4                       1067
#define IDC_LABEL18                     1068
#define IDC_SN_TYPE                     1068
#define IDC_LABEL5                      1069
#define IDC_SN_LENGTH                   1069
#define IDC_LABEL51                     1069
#define IDC_LABEL21                     1070
#define IDC_ONE_UP                      1070
#define IDC_LABEL54                     1070
#define IDC_LABEL31                     1071
#define IDC_TWO_UP                      1071
#define IDC_LABEL55                     1071
#define IDC_LABEL32                     1072
#define IDC_LABEL52                     1072
#define IDC_LABEL56                     1072
#define IDC_LABEL37                     1073
#define IDC_ONE_NOSEPIECE               1073
#define IDC_PANEL_COUNT                 1074
#define IDC_LABEL38                     1074
#define IDC_TWO_NOSEPIECES              1074
#define IDC_LABEL_COUNT                 1075
#define IDC_DELETE                      1075
#define IDC_LABEL34                     1076
#define IDC_CURRENT_SN                  1076
#define IDC_EDIT                        1076
#define IDC_LABEL_RUN_SERIAL            1079
#define IDC_2UP_JOB                     1079
#define IDC_MANUFACTURING_SITE          1080
#define IDC_COUNTRY                     1081
#define IDC_USESTATICDATECODE           1084
#define IDC_STATICDATECODE              1085
#define IDC_LABEL_MATCH                 1086
#define IDC_TEXTBOX1                    1090
#define IDC_JOB_INFO                    1096
#define IDC_SCANNER_LABEL               1097
#define IDC_SAVEASNEW                   1099
#define IDC_CMD_HOLD                    1099
#define IDC_SET_OUTPUT_ADDRESS          1099
#define IDC_LABEL4                      1101
#define IDC_PRINTER_DIAGNOSTICS         1101
#define IDC_SET_INPUT_ADDRESS           1101
#define IDC_LABEL30                     1102
#define IDC_LABEL8                      1103
#define IDC_STATIC_INPUT_BIT_0          1103
#define IDC_LABEL14                     1104
#define IDC_LABEL6                      1109
#define IDC_DEVICE_LIST                 1114
#define IDC_PORT_ID                     1115
#define IDC_SETTINGS                    1116
#define IDC_INBUFFER_SIZE               1118
#define IDC_STATIC_INPUT_BIT_15         1118
#define IDC_CMD_SETUPSYSTEM             1119
#define IDC_OUTBUFFER_SIZE              1119
#define IDC_STATIC_INPUT_BIT_16         1119
#define IDC_INPUT_ADDRESS               1120
#define IDC_OUTPUT_ADDRESS              1121
#define IDC_SPEED                       1122
#define IDC_STATIC_INPUT_BIT_17         1122
#define IDC_DESCRIPTION                 1123
#define IDC_ACCELERATION                1123
#define IDC_STATIC_INPUT_BIT_18         1123
#define IDC_CONVEYOR_INPUT_ADDRESS      1124
#define IDC_STATIC_INPUT_BIT_19         1124
#define IDC_ENABLE_STATS                1125
#define IDC_PANEL_DIMX                  1125
#define IDC_CONVEYOR_OUTPUT_ADDRESS     1125
#define IDC_STATIC_INPUT_BIT_20         1125
#define IDC_PANEL_DIMY                  1126
#define IDC_UPDATE_INTERVAL             1126
#define IDC_TRIGGER_DELAY               1126
#define IDC_STATIC_INPUT_BIT_21         1126
#define IDC_LABEL_POSITIONS             1127
#define IDC_STATIC_INPUT_BIT_22         1127
#define IDC_STATIC_INPUT_BIT_23         1128
#define IDC_USEDATABASE                 1129
#define IDC_STATIC_INPUT_BIT_25         1129
#define IDC_X_ORIGIN                    1130
#define IDC_USEDESIGNERLABEL            1130
#define IDC_STATIC_INPUT_BIT_24         1130
#define IDC_Y_ORIGIN                    1131
#define IDC_STATIC_INPUT_BIT_26         1131
#define IDC_X_PARK_POSITION             1132
#define IDC_PARTNUMBER                  1132
#define IDC_STATIC_INPUT_BIT_27         1132
#define IDC_ORGIN_TEACH                 1169
#define IDC_CMBPOINTTYPE                1170
#define IDC_PARK_TEACH                  1170
#define IDC_OLD_XPOS                    1171
#define IDC_RESTPOSITION_TEACH          1171
#define IDC_OLD_YPOS                    1172
#define IDC_NEW_XPOS                    1173
#define IDC_CANCEL                      1174
#define IDC_NEW_YPOS                    1174
#define IDC_UPDATE_JOB                  1175
#define IDC_TEMPLATE_NAME               1175
#define IDC_DELETEJOB                   1175
#define IDC_LEFT_BUTTON                 1175
#define IDC_EDIT_PANEL_LABEL            1176
#define IDC_RIGHT_BUTTON                1176
#define IDC_TEACH_PPICK                 1176
#define IDC_STEP_SIZE                   1177
#define IDC_TEACH_PICK                  1177
#define IDC_ABOUTBUTTON                 1178
#define IDC_SINGLE_TRIGGER              1178
#define IDC_TOP_BUTTON                  1178
#define IDC_STATISTICS_FILE             1179
#define IDC_CONTINUOUS_TRIGGER          1179
#define IDC_BOTTOM_BUTTON               1179
#define IDC_EDT_JOG_SPEED               1180
#define IDC_MANUAL_FEED                 1181
#define IDC_LBLMETRICS                  1182
#define IDC_LBLJOBDETAILS               1183
#define IDC_RESET_JULIAN                1183
#define IDC_AUTO_REPICKS                1185
#define IDC_AUTO_RESCANS                1186
#define IDC_LABEL24                     1187
#define IDC_REFRESH_LIST                1188
#define IDC_PANEL_QUANTITY              1189
#define IDC_LABEL25                     1189
#define IDC_CUSTOMER                    1190
#define IDC_LABEL36                     1190
#define IDC_PRODUCT_CODE                1190
#define IDC_CLOSE_MC_DIAGNOSTICS        1192
#define IDC_CLOSE_SCANNER_DIAGNOSTICS   1193
#define IDC_CLOSE_PRINTER_DIAGNOSTICS   1194
#define IDC_SET_DEFAULTS                1299
#define IDC_PRINTER_STATUS              1300

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        210
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1184
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
