#ifndef __SIMULATIONCONSTANTS_

#define	SIMULATEPRINTER				0x01
#define SIMULATEUPSTEAMSCANNER		0x02
#define SIMULATELABELSCANNER		0x04
#define SIMULATEDIOCONTROLLER		0x08
#define SIMULATESERIALCONTROLLER	0x10
#define SIMULATEPCBASEDCONTROLLER	0x20

#endif